#!/bin/bash
# Remind user if they connected capture card properly or not
# This works for CSI v2/v3-rpi4, USB v2-rpi4, and v2-zerow (CSI only)
# ... script will check the relevant dmesg entries for USB or CSI
MODEL=$( pacman -Q | grep kvmd-platform | cut -d'-' -f4 )
if [[ "$MODEL" == "hdmiusb" ]]; then
        # Make sure MACROSILICON controller on USB-HDMI is plugged in to 1-1.4
        # show the last MACROSILICON entry in case user moved the usb dongle
        # ... this way, script will always give the most recent check
        # ... NOTE:  You can move usb dongle anytime without powering down Pi
        USBHDMI=$( dmesg | grep -i MACROSILICON | grep 'usb ' | tail -1 )
        if [[ $( echo $USBHDMI | grep 1-1.4 | wc -l ) -gt 0 ]]; then
                printf "USB HDMI dongle is connected properly.\n"
        else
                printf "Pls put USB HDMI dongle to bottom USB2.0 port on Pi4.\n"
        fi
        echo "$USBHDMI"
else
        # PiKVM uses CSI bridge capture so check to make sure it's in the CAMERA port
        # ... NOTE:  Poweroff Pi before moving CSI cable
        CSI=$( dmesg | grep tc35 | grep -v Modules )
        if [[ $( echo $CSI | grep not | wc -l ) -gt 0 ]]; then
                printf "Pls put CSI bridge into Pi CAMERA port.\n"
        else
                printf "CSI 2 bridge is connected properly.\n"
        fi
        echo "$CSI"
fi
